<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nutrimind.Domain\Nutrimind.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Supabase" Version="0.12.0" />
  </ItemGroup>

</Project>
