<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nutrimind.Domain\Nutrimind.Domain.csproj" />
    <ProjectReference Include="..\Nutrimind.Application\Nutrimind.Application.csproj" />
  </ItemGroup>

</Project>
