<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1593cd6b-1b85-4e22-b9ab-6d6fffda1437</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nutrimind.Application\Nutrimind.Application.csproj" />
    <ProjectReference Include="..\Nutrimind.Infrastructure.Supabase\Nutrimind.Infrastructure.Supabase.csproj" />
    <ProjectReference Include="..\Nutrimind.Infrastructure.OpenFoodFacts\Nutrimind.Infrastructure.OpenFoodFacts.csproj" />
  </ItemGroup>

</Project>
